final String tableAdress = 'adress';

class AdressModel {
  late final int? adressId;  //beacause rightnow id is autogenerated by local db
  late final String adressTitle;
  // final String email;
  // final String body;

  AdressModel({ this.adressId, required this.adressTitle,} );


  String get getId =>adressId.toString();
  String get getAdressTitle => adressTitle;


  static AdressModel fromDictionary(Map<String, Object?> json) => AdressModel(
    adressId: json[AdressFields.id] as int?,
    adressTitle: json[AdressFields.adressTitle] as String,
  );

  Map<String, Object?> toDictonary() => {
    AdressFields.id: adressId,
    AdressFields.adressTitle : adressTitle
  };

  AdressModel copy({
     int? id,
     String? title,
  }) =>
      AdressModel(
        adressId: id??this.adressId,
        adressTitle: title??this.adressTitle,
      );
  //
  // CommentSample({this.postId, this.id, this.name, this.email, this.body});
  //
  // CommentSample.fromJson(Map<String, dynamic> json) {
  //   postId = json['postId'];
  //   id = json['id'];
  //   name = json['name'];
  //   email = json['email'];
  //   body = json['body'];
  // }
  //
  // Map<String, dynamic> toJson() {
  //   final Map<String, dynamic> data = new Map<String, dynamic>();
  //   data['postId'] = this.postId;
  //   data['id'] = this.id;
  //   data['name'] = this.name;
  //   data['email'] = this.email;
  //   data['body'] = this.body;
  //   return data;
  // }
}


class AdressFields{
  static final List<String> values = [
    id,adressTitle
  ];

  static final String id = 'id';
  static final String adressTitle = 'title';
}